#!/usr/bin/python
# -*- coding: utf-8 -*-
# https://www.youtube.com/watch?v=4fHL6BpJrC4
# Ansteuerung eines bipolaren 4 Phasen-Schrittmotors mit einem ULN2003 Controller Board

import time
import RPi.GPIO as GPIO

#GPIOs unter GPIO-BOARD_Nummern ansprechen

GPIO.setmode(GPIO.BOARD)

# Verwendete Pins am Rapberry Pi
# A, B, C und D = Ausgangspins für Schrittmotor starten

A=7 # IN1
B=11 # IN3
C=13 # IN2
D=15 # IN4

"""
step  1  2  3  4  5  6  7  8
      
Pin1  x  x                 x
Pin2     x  x  x
Pin3           x  x  x
Pin4                 x  x  x

"""

# Pins A, B, C, D, Schrittmotor als Ausgänge definieren
def GPIO_SETUP(a,b,c,d):
    GPIO.output(A, a)
    GPIO.output(B, b)
    GPIO.output(C, c)
    GPIO.output(D, d)
    time.sleep(0.001)

def RIGHT_TURN(deg):

    full_circle = 510.0 """ Das mann prüfen muss """
    degree = full_circle/360*deg
    GPIO_SETUP(0,0,0,0)
	
	while degree > 0.0:
        GPIO_SETUP(1,0,0,0)
        GPIO_SETUP(1,1,0,0)
        GPIO_SETUP(0,1,0,0)
        GPIO_SETUP(0,1,1,0)
        GPIO_SETUP(0,0,1,0)
        GPIO_SETUP(0,0,1,1)
        GPIO_SETUP(0,0,0,1)
        GPIO_SETUP(1,0,0,1)
        degree -= 1

def LEFT_TURN(deg):

    full_circle = 510.0
    degree = full_circle/360*deg
    GPIO_SETUP(0,0,0,0)

    while degree > 0.0:
        GPIO_SETUP(1,0,0,1)
        GPIO_SETUP(0,0,0,1)
        GPIO_SETUP(0,0,1,1)
        GPIO_SETUP(0,0,1,0)
        GPIO_SETUP(0,1,1,0)
        GPIO_SETUP(0,1,0,0)
        GPIO_SETUP(1,1,0,0)
        GPIO_SETUP(1,0,0,0)
        degree -= 1

#MAIN #########################


RIGHT_TURN(90)
LEFT_TURN(90)
RIGHT_TURN(360)
GPIO_SETUP(0,0,0,0)

       
except KeyboardInterrupt:
   print("Programm vom User gestoppt")
   GPIO.cleanup()
                 
While ()
